PHP Laravel Framework (with VueJS)/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::auth();

// Public Shop
Route::get('/store', 'Kiosk\ShopController@index');


Route::group(['prefix' => '/', 'middleware' => 'auth'], function() {
	Route::get('/', function () {
	    return redirect('dashboard');
	});

	Route::group(['prefix' => 'messages'], function() {
		Route::get('/', ['as' => 'message_board', 'uses' => 'MessageBoardController@index']);
		Route::get('create', ['as' => 'message_create', 'uses' => 'MessageBoardController@create']);
		Route::post('store', ['as' => 'message_store', 'uses' => 'MessageBoardController@store']);
		Route::get('edit/{id}', ['as' => 'message_edit', 'uses' => 'MessageBoardController@edit']);
		Route::get('show/{id}', ['as' => 'message_show', 'uses' => 'MessageBoardController@show']);
		Route::post('update/{id}', ['as' => 'message_update', 'uses' => 'MessageBoardController@update']);
		Route::get('pin/{id}', ['as' => 'message_pin', 'uses' => 'MessageBoardController@pin']);
		Route::get('unpin/{id}', ['as' => 'message_unpin', 'uses' => 'MessageBoardController@unpin']);
		Route::get('delete/{id}', ['as' => 'message_destroy', 'uses' => 'MessageBoardController@destroy']);
	});

	// Clients
	Route::group(['prefix' => 'clients', 'middleware' => 'web'],function(){
	    Route::get('/', ['as' => 'clients', 'uses' => 'ClientController@index']);
	    Route::get('/{id}', ['as'=> 'client_by_location', 'uses'=>'ClientController@index']);
	    Route::get('plan/{id}', ['as' => 'client_by_plan', 'uses'=>'ClientController@plan']);
	    Route::get('profile/{id}', ['as' => 'client_profile', 'uses' => 'ClientController@profile']);
	    Route::get('edit/{id}', ['as' => 'client_edit', 'uses' => 'ClientController@edit']);
	    Route::post('store',['as' => 'client_store', 'uses' => 'ClientController@store']);
	    Route::post('update/{id}',['as' => 'client_update', 'uses' => 'ClientController@update']);
	    Route::post('profile/{id}', ['as' => 'client_profile', 'uses' => 'ClientController@profile']);
	    Route::get('delete/{id}', ['as' => 'client_destroy', 'uses' => 'ClientController@destroy']);
	});

	//
	Route::get('/logout', ['as' => 'logout', 'uses' => 'HomeController@logout']);
	Route::group(['prefix' => 'permissions', 'middleware' => 'web'],function(){
	    Route::get('/', ['as' =>'permission_list', 'uses' => 'PermissionController@index']);
	    Route::get('/add', ['as' =>'permission_add', 'uses' => 'PermissionController@create']);
	    Route::post('/store', ['as' =>'permission_store', 'uses' => 'PermissionController@store']);
	    Route::get('/edit/{id}', ['as' =>'permission_edit', 'uses' => 'PermissionController@edit']);
	    Route::post('/update/{id}', ['as' =>'permission_update', 'uses' => 'PermissionController@update']);
	    Route::get('/delete/{id}',	['as' =>'permission_delete',    'uses' => 'PermissionController@destroy']);
	});

	Route::group(['prefix' => 'roles', 'middleware' => 'web'],function(){
	    Route::get('/', ['as' =>'role_list', 'uses' => 'RoleController@index']);
	    Route::get('/add', ['as' =>'role_add', 'uses' => 'RoleController@create']);
	    Route::post('/store', ['as' =>'role_store', 'uses' => 'RoleController@store']);
	    Route::get('/edit/{id}', ['as' =>'role_edit', 'uses' => 'RoleController@edit']);
	    Route::post('/update/{id}', ['as' =>'role_update', 'uses' => 'RoleController@update']);
	    Route::get('/delete/{id}',	['as' =>'role_delete',    'uses' => 'RoleController@destroy']);
	});

	Route::group(['prefix' => 'users', 'middleware' => 'web'],function(){
	    Route::get('/',['as' => 'users', 'uses' => 'UserController@index']);
	    Route::get('/create',['as' => 'user_create', 'uses' => 'UserController@create']);
	    Route::get('/edit/{id}',['as' => 'user_edit', 'uses' => 'UserController@edit']);

	    Route::post('/store',['as' => 'user_store', 'uses' => 'UserController@save']);
	    Route::post('/update/{id}',['as' => 'user_update', 'uses' => 'UserController@update']);
	    Route::get('/delete/{id}',['as' => 'user_destroy', 'uses' => 'UserController@destroy']);

	    Route::get('/profile/{id?}',['as' => 'user_show', 'uses' => 'UserController@show']);

	    Route::post('/assign_role/{id}',['as' => 'user_assign_role', 'uses' => 'UserController@assign_role']);
	});

	Route::group(['prefix' => 'logs', 'middleware' => 'web'],function(){
	    Route::get('/',['as' => 'logs', 'uses' => 'LogController@index']);
	    Route::get('/user/{id}',['as' => 'user_logs', 'uses' => 'LogController@getUserLog']);
	});


	Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);

	Route::get('fetch-locations', 'LocationController@fetchLocations');
	Route::group(['prefix' => 'location'], function() {
		Route::get('/', ['as' => 'location', 'uses' => 'LocationController@index']);
		Route::get('edit/{id}', ['as' => 'edit-location', 'uses' => 'LocationController@edit']);
		Route::post('store', ['as' => 'store-location', 'uses' => 'LocationController@store']);
		Route::post('update/{id}', ['as' => 'update-location', 'uses' => 'LocationController@update']);
		Route::get('trash/{id}', ['as' => 'location-trash', 'uses' => 'LocationController@trash']);
		Route::get('users/{id}', ['as' => 'location-users', 'uses' => 'LocationController@getUsers']);
	});

	Route::group(['prefix' => 'membership', 'middleware'=>'web'], function() {
		Route::get('/', ['as' => 'membership', 'uses' => 'MembershipController@index']);
		Route::get('edit/{id}', ['as' => 'membership-edit', 'uses' => 'MembershipController@edit']);
		Route::post('store', ['as'=>'membership-store', 'uses'=>'MembershipController@store']);
		Route::post('update/{id}', ['as'=>'membership-update', 'uses'=>'MembershipController@update']);
		Route::get('delete/{id}', ['as' => 'membership-destroy', 'uses' => 'MembershipController@destroy']);
	});

	Route::group(['prefix' => 'amenities', 'middleware' => 'web'], function() {
		Route::get('/', ['as' => 'amenities', 'uses' => 'AmenityController@index']);
		Route::get('edit/{id}', ['as' => 'amenities-edit', 'uses' => 'AmenityController@edit']);
		Route::post('store', ['as'=>'amenities-store', 'uses'=>'AmenityController@store']);
		Route::post('update/{id}', ['as'=>'amenities-update', 'uses'=>'AmenityController@update']);
		Route::get('delete/{id}', ['as' => 'amenities-destroy', 'uses' => 'AmenityController@destroy']);
	});

	Route::group(['prefix' => 'events'], function() {
		Route::get('/{id?}', ['as' => 'events', 'uses' => 'EventsController@index']);
		Route::get('/fetch/{id}', ['as' => 'fetch_events', 'uses' => 'EventsController@getEventsByLocation']);
		Route::get('/edit/{id}', 'EventsController@edit');
		Route::get('/show/{id}', ['as' => 'show_events', 'uses' => 'EventsController@show']);
		Route::post('/add', 'EventsController@store');
		Route::post('/update/{id}', 'EventsController@update');
		Route::get('/delete/{id}', 'EventsController@destroy');
	});

	Route::group(['prefix' => 'rooms'], function() {
		Route::group(['prefix' => 'management'], function() {
			Route::get('/{id?}', ['as' => 'manage_room',  'uses' => 'RoomManageController@index']);
			Route::post('/store', ['as' => 'add_room',  'uses' => 'RoomManageController@store']);
			Route::get('/edit/{id}', ['as' => 'edit_room',  'uses' => 'RoomManageController@edit']);
			Route::post('/update/{id}', ['as' => 'update_room',  'uses' => 'RoomManageController@update']);
			Route::get('/delete/{id}', ['as' => 'delete_room',  'uses' => 'RoomManageController@destroy']);
		});

		Route::group(['prefix' => 'reservation'], function() {
			Route::get('/me', ['as' => 'user_reservations', 'uses' => 'RoomReservationController@user']);
			Route::get('/user/{id}', ['as' => 'this_user_reservations', 'uses' => 'RoomReservationController@user']);
			Route::post('/store', ['as' => 'store_reservations', 'uses' => 'RoomReservationController@store']);
			Route::get('/edit/{id}', ['as' => 'user_reservations', 'uses' => 'RoomReservationController@edit']);
			Route::post('/update/{id}', ['as' => 'update_reservations', 'uses' => 'RoomReservationController@update']);

			Route::group(['prefix' => 'request'], function() {
				Route::get('/reserve/{id}', ['as' => 'reservation_item', 
											 'uses' => 'RoomReservationController@show']);
				Route::get('/confirm/{id}', ['as'=>'reservation_confirm', 
											 'uses'=>'RoomReservationController@confirm']);
				Route::post('/cancel/{id}', ['as'=>'reservation_cancel', 
											'uses'=>'RoomReservationController@cancel']);
				Route::post('/reject/{id}', ['as'=>'reservation_reject', 
											'uses'=>'RoomReservationController@reject']);

				Route::get('/{location?}/{room?}', ['as' => 'reservation_request', 
												   'uses' => 'RoomReservationController@requests']);

			});

			Route::get('/{id?}', ['as' => 'all_reservations', 'uses' => 'RoomReservationController@all']);
		});

		Route::get('/fetch/{location}/{room?}', [
							'as' => 'fetch_schedules', 
							'uses' => 'RoomReservationController@getScheduleByRoom']);
		Route::get('/fetch-room/{id}', [
							'as' => 'fetch_room_schedules', 
							'uses' => 'RoomReservationController@getScheduleByLocation']);

		Route::get('/{location}/{room?}', ['as' => 'rooms', 'uses' => 'RoomReservationController@index']);
	});

	Route::group(['prefix' => 'shop'], function() {
		Route::get('/', ['as'=>'shop', 'uses'=>'Kiosk\ShopController@index']);

		// Shop Controllers
	    Route::group(['prefix' => 'dashboard'], function() {
	    	Route::get('/', ['as'=>'shop-dashboard' , 'uses'=>'Kiosk\ShopController@dashboard']);
	    	Route::get('fetch-categories', 'Kiosk\ShopController@fetchCategories');

PHP Laravel Framework (with VueJS)/app/Log.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Log extends Model
{
    public function user()
    {
        return $this->belongsToMany(User::class);
    }
}

PHP Laravel Framework (with VueJS)/app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

use Auth;

use App\Role;

class User extends Authenticatable
{
    use HasRoles;
    use SoftDeletes;
    
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'nickname', 'username', 'email', 'password', 'parent', 'status', 'remember_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        if (Auth::user()) {
            static::updating(function($user) {
                $user->logs()->attach(Auth::user()->id, ['module_name' => 'User', 'log' => Auth::user()->first_name . ' ' . Auth::user()->last_name . ' is updating ' . $user->first_name . ' ' . $user->last_name ]);
            });

            static::creating(function($user){
                $user->logs()->attach(Auth::user()->id, ['module_name' => 'User', 'log' => Auth::user()->first_name . ' ' . Auth::user()->last_name . ' is creating ' . $user->first_name . ' ' . $user->last_name ]);
            });

            static::deleting(function($user){
                $user->logs()->attach(Auth::user()->id, ['module_name' => 'User', 'log' => Auth::user()->first_name . ' ' . Auth::user()->last_name . ' is deleting ' . $user->first_name . ' ' . $user->last_name ]);
            });
        }
    }

    public function Role(){
        return $this->belongsToMany(Role::class);
    }

    public function assignedRole($id)
    {
        return $this->roles()->save(
            Role::where('id',$id)->firstOrFail()
        );
    }

    public function usermeta(){
        return $this->hasMany(UserMeta::class);
    }

    public function logs(){
        return $this->belongsToMany(User::class, 'logs', 'module_id')
            ->withTimestamps()
            ->latest('pivot_updated_at');
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function LocationUser()
    {
        return $this->hasOne(LocationUser::class);
    }
    
    public function PersonalInfo()
    {
        // $this->hasOne('App\PersonalInfo','user_id','id');
        return $this->hasOne(PersonalInfo::class);
    }

    public function UserMembership()
    {
        return $this->hasOne(UserMembership::class);
    }

    public function RoomReservation()
    {
        return $this->hasMany(RoomReservation::class);
    }

}

PHP Laravel Framework (with VueJS)/app/Http/Controllers/LogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use RoboPlanner\Repositories\LogRepository;

class LogController extends Controller
{
    //
    protected $log;
    protected $auth;
    private $message;

    public function __construct(LogRepository $log)
    {
        $this->log = $log;
        $this->log->setListener($this);
    }

    public function index(Request $request){
        $data['logs']   = $this->log->getLogs($request);
//        return view('roboplanner.errors.403');

        $data['search']	= trim($request->input('search'));
        $data['sort']   = ($request->input('sort') == 'asc')? 'desc' : 'asc';
        $data['page_number']= $request->input('page');
        return view('logs.index', $data);
    }

    public function getUserLog($id){

    }

    public function delete($id){

    }
}

PHP Laravel Framework (with VueJS)/resources/views/logs/index.blade.php
@extends('roboplanner.layouts.template')

@section('title', 'User Logs | ')
@section('pageTitle', 'User Logs')

@section('styles')
    {{--<link rel="stylesheet" href="{{ asset('css/jquery.steps.css')  }}">--}}
    <link rel="stylesheet" href="{{ asset("js/jquery-confirm/css/jquery-confirm.css") }}">
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumb">
            <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="active">Logs</li>
        </ul>
    </div>
</div>

<div class="container">
    
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1>Logs</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default bootstrap-admin-no-table-panel">
                <div class="panel panel-default bootstrap-admin-no-table-panel">
                    <div class="panel-heading">
                        <div class="text-muted bootstrap-admin-box-title">Logs List</div>
                    </div>
                    <div class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
                        <div class="row">
                            <div class="col-sm-6">

                            </div>
                            <div class="col-sm-6">
                                <form method="get" action="{{ route('users')}}">
                                    <div class="search form-group" style="float:right">
                                        <div class="input-group">
                                            <span class="input-group-addon" id="basic-addon1"><i class="fa fa-search"></i></span>
                                            <input type="text" class="search-form form-control" placeholder="Search" name="search" aria-describedby="basic-addon1" value="{{ $search }}">
                                            <span class="input-group-btn clearer">
                                                <button class="btn btn-primary" type="button" style="border:none; background-color:transparent; z-index:999; margin-left:-35px; font-size:10px"><a href="{{ route('users')}}">X</a></button>
                                            </span>
                                            <span class="input-group-btn">
                                                <button class="btn btn-secondary" type="submit">Go</button>
                                            </span>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <table width="100%" class="table table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th width="15%"></th>
                                        <th width="25%"><a href="{{ route('users').'?page='.$page_number.'&search='.$search.'&order_by=email&sort='.$sort }}">Email</a></th>
                                        <th width="25%"><a href="{{ route('users').'?page='.$page_number.'&search='.$search.'&order_by=first_name&sort='.$sort }}">First Name</a></th>
                                        <th width="25%"><a href="{{ route('users').'?page='.$page_number.'&search='.$search.'&order_by=last_name&sort='.$sort }}">Last Name</a></th>
                                        <th width="10%"><a href="">Position</a></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($users as $row)
                                        <tr>

                                            <td style="text-align:center">
                                                <div class="dropdown">
                                                    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown">Options
                                                        <span class="caret"></span></button>
                                                    <ul class="dropdown-menu">
                                                        <li>
                                                            <a title="View Profile of {{ $row->full_name  }}" href = "{{ route('user_show', $row->id) }}">
                                                                <i class="fa fa-lg fa-user"></i>View Profile
                                                            </a>
                                                        </li>
                                                        @can('assign_role')
                                                        <li>
                                                            <a title="Assign role to {{ $row->full_name  }}" href="" data-toggle="modal" data-target="#{{ $row->id  }}_role_modal">
                                                                <i class="fa fa-lg fa-eject"></i> Assign Role
                                                            </a>
                                                        </li>
                                                        @endcan
                                                        @can('update_user')
                                                        <li>
                                                            <a title="Edit User {{ $row->full_name  }}" href = "{{ route('user_edit', $row->id) }}">
                                                                <i class="fa fa-lg fa-pencil-square-o"></i> Edit User</a>
                                                        </li>
                                                        @endcan
                                                        @can('delete_user')
                                                        @if(Auth::user()->id != $row->id)
                                                            <li>
                                                                <a title="Delete User {{ $row->full_name  }}" href = "{{ route('user_destroy', $row->id) }}" class="delete_confirmation">
                                                                    <i class="fa fa-lg fa-user-times"></i> Delete User</a>
                                                            </li>
                                                        @endif
                                                        @endcan
                                                    </ul>
                                                </div>
                                                <!-- Modal -->
                                                <div id="{{ $row->id  }}_role_modal" class="modal fade" role="dialog">
                                                    <div class="modal-dialog">
                                                        <!-- Modal content-->
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                <h4 class="modal-title"><label for="status">Assign Role</label></h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <form action="{{ route('user_assign_role', $row->id) }}" method="post">
                                                                    <select name="role" id="role" class="form-control">
                                                                        <option value="" selected disabled>-Choose Role-</option>
                                                                        @foreach(App\Role::all() as $role)
                                                                            <option value="{{ $role->id  }}" @if($row->Role()->first()->id == $role->id))) selected @endif>{{ $role->name }}</option>
                                                                        @endforeach
                                                                    </select>

                                                                    <br/>
                                                                    <button class="btn btn-primary" type="submit">Submit</button>
                                                                    {!! csrf_field() !!}
                                                                </form>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                            </td>
                                            <td>{{ $row->email }}</td>
                                            <td>{{ $row->first_name  }}</td>
                                            <td>{{ $row->last_name  }}</td>
                                            <td>{{ $row->PersonalInfo()->position or "None" }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>

                                </table>
                                @if(isset($users) && $users->count() == 0)
                                    <div style="text-align:center; color:#333; font-size:18px">No records to show</div>
                                    @if($search)
                                        <div style="text-align:center; color:#333; font-size:18px">for {{ $search }}</div>
                                    @endif
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

@section('scripts')
    <script src="{{ asset("js/jquery-confirm/js/jquery-confirm.js") }}"></script>
    <script>
        //        $.confirm();
        $('.delete_confirmation').on('click',function(){
            confirm('Are you sure you want to delete this User?');
        });
    </script>
@stop